services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/react-docker:delegated
      - /node_modules
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
